coverage:
  ignore:
    - Tests/ParseServerSwiftTests/.*
  status:
    patch:
      default:
        target: auto
    changes: false
    project:
      default:
        target: auto
comment:
  require_changes: true
