coverage:
  ignore:
    - Tests/ParseServerSwiftTests/.*
  status:
    patch:
      default:
        target: 46
    changes: false
    project:
      default:
        target: 43
comment:
  require_changes: true
