coverage:
  ignore:
    - Tests/ParseServerSwiftTests/.*
  status:
    patch:
      default:
        target: 17
    changes: false
    project:
      default:
        target: 33
comment:
  require_changes: true
