disabled_rules:
  - file_length
  - identifier_name
  - blanket_disable_command
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - DerivedData
  - .build
  - .dependencies
